name: flixy
description: A Video On Demand Streaming App(VOD)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  provider: ^6.0.2
  shared_preferences: ^2.0.14
  go_router: ^4.4.1
  smooth_page_indicator: ^1.0.0+2
  intl_phone_field: ^3.1.0
  intl_phone_number_input: ^0.7.0+2
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
